- name: Check pywinrm version on localhost
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Upgrade pywinrm using pip
      ansible.builtin.pip:
        name: pywinrm
        state: latest
        executable: pip3
        
    - name: Run pip command to get pywinrm version
      ansible.builtin.command: "pip3 show pywinrm"
      register: pywinrm_version
      ignore_errors: true

    - name: Display pywinrm version
      ansible.builtin.debug:
        msg: "{{ pywinrm_version.stdout_lines | default(['pywinrm not installed']) }}"
