- hosts: all
  gather_facts: false

  vars: 
    ansible_winrm_shell: powershell

  tasks:
    - name: Upgrade pywinrm in the Ansible environment
      ansible.builtin.pip:
        name: pywinrm
        state: latest
        executable: "{{ ansible_python.executable | default('pip3') }}"
      delegate_to: localhost

    - name: Display pywinrm version
      ansible.builtin.command: "{{ ansible_python.executable }} -m pip show pywinrm"
      delegate_to: localhost
      register: pywinrm_version

    - name: Show updated pywinrm version
      ansible.builtin.debug:
        msg: "{{ pywinrm_version.stdout_lines }}"

    - name: Run a Windows command
      win_shell: echo "Debug Windows Task"

    - name: "18.6.5.1 | PATCH | Ensure Enable Font Providers is set to Disabled"
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
        name: EnableFontProviders
        data: 0
        type: dword
