#playbook to test out the leave temp files around
---
- hosts: all
  gather_facts: false

  vars: 
    keep_remote_files: true

  tasks: 
  - name: Run a Windows command
    win_shell: echo "Debug Windows Task"

  - name: "18.6.5.1 | PATCH | Ensure Enable Font Providers is set to Disabled"
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\System
      name: EnableFontProviders
      data: 0
      type: dword
